/**
 * seo/theme.mjs
 * ---------------------------------------------------------------------------
 * Single source of truth for the look & feel of every SEO page (static pages
 * generated by scripts/generate-seo-pages.mjs AND the SSR server in
 * seo/ssr-server.mjs). Written as one external stylesheet so 50k+ question
 * pages don't each carry ~7 KB of duplicated inline CSS.
 *
 * Design goals vs. the usual Bengali MCQ sites (Sattacademy, চর্চা, porikha):
 *   - real Bengali webfonts (serif display for the question, sans for body)
 *   - question is the hero: big, airy line-height, no visual noise
 *   - options read as a scan-able list with a clear letter badge
 *   - the correct answer + explanation are visually separated and calm
 *   - chips/badges are real links -> deep internal linking
 *   - full dark-mode + reduced-motion support
 */

export const SITE = 'https://www.porikkhangon.app';
export const BRAND = 'পরীক্ষাঙ্গন';
export const BRAND_LATIN = 'Porikkhangon';

/** Google Fonts used by the SEO pages. Preconnected + swapped in the shell. */
export const FONT_CSS_URL =
  'https://fonts.googleapis.com/css2?family=Hind+Siliguri:wght@300;400;500;600;700&family=Noto+Serif+Bengali:wght@500;600;700&family=Inter:wght@500;600;700&display=swap';

export const THEME_CSS = `
/* ==========================================================================
   পরীক্ষাঙ্গন — SEO page theme
   ========================================================================== */
:root{
  --bg:#f5f6fa;
  --surface:#ffffff;
  --surface-2:#fafbfd;
  --ink:#0f172a;
  --ink-2:#334155;
  --muted:#64748b;
  --muted-2:#94a3b8;
  --line:#e6e9f2;
  --line-2:#eef1f7;
  --brand:#ff5200;
  --brand-2:#ff7a33;
  --brand-ink:#c53d00;
  --brand-soft:#fff2eb;
  --brand-line:#ffd9c7;
  --ok:#0f9d58;
  --ok-ink:#0b7a44;
  --ok-soft:#effaf3;
  --ok-line:#b6e9cd;
  --gold-ink:#92400e;
  --gold-soft:#fff8ec;
  --gold-line:#f5dfae;
  --blue-soft:#eef4ff;
  --blue-line:#cfddf7;
  --blue-ink:#1d4ed8;
  --radius:18px;
  --radius-sm:12px;
  --shadow-sm:0 1px 2px rgba(15,23,42,.05);
  --shadow:0 1px 2px rgba(15,23,42,.04), 0 12px 32px -16px rgba(15,23,42,.22);
  --shadow-lg:0 2px 4px rgba(15,23,42,.05), 0 24px 48px -24px rgba(15,23,42,.30);
  --sans:'Hind Siliguri','Noto Sans Bengali',system-ui,-apple-system,'Segoe UI',sans-serif;
  --serif:'Noto Serif Bengali','Hind Siliguri',Georgia,serif;
  --latin:'Inter','Hind Siliguri',system-ui,sans-serif;
}

@media (prefers-color-scheme:dark){
  :root{
    --bg:#0b0f17;
    --surface:#121826;
    --surface-2:#0f1522;
    --ink:#f1f5f9;
    --ink-2:#dbe3ee;
    --muted:#93a1b5;
    --muted-2:#6b7a90;
    --line:#232c3e;
    --line-2:#1b2333;
    --brand:#ff6a24;
    --brand-2:#ff8b52;
    --brand-ink:#ffb493;
    --brand-soft:#2a1408;
    --brand-line:#4a2410;
    --ok:#34d399;
    --ok-ink:#6ee7b7;
    --ok-soft:#0d2018;
    --ok-line:#1d4b36;
    --gold-ink:#fcd34d;
    --gold-soft:#241a08;
    --gold-line:#4a360f;
    --blue-soft:#101a2e;
    --blue-line:#22345c;
    --blue-ink:#93b4ff;
    --shadow-sm:0 1px 2px rgba(0,0,0,.4);
    --shadow:0 1px 2px rgba(0,0,0,.3), 0 12px 32px -16px rgba(0,0,0,.7);
    --shadow-lg:0 2px 4px rgba(0,0,0,.35), 0 24px 48px -24px rgba(0,0,0,.8);
  }
}

*,*::before,*::after{box-sizing:border-box}
html{-webkit-text-size-adjust:100%}
body{
  margin:0;
  background:var(--bg);
  color:var(--ink);
  font-family:var(--sans);
  font-size:17px;
  line-height:1.85;
  -webkit-font-smoothing:antialiased;
  -moz-osx-font-smoothing:grayscale;
  text-rendering:optimizeLegibility;
}
img{max-width:100%;height:auto}
a{color:var(--brand-ink);text-decoration:none}
a:hover{text-decoration:underline}
:focus-visible{outline:2px solid var(--brand);outline-offset:3px;border-radius:6px}

/* ---------- top bar ----------------------------------------------------- */
.topbar{
  position:sticky;top:0;z-index:20;
  background:color-mix(in srgb,var(--surface) 88%,transparent);
  backdrop-filter:saturate(160%) blur(10px);
  border-bottom:1px solid var(--line);
}
.topbar-in{
  max-width:1000px;margin:0 auto;padding:11px 18px;
  display:flex;align-items:center;gap:14px;justify-content:space-between;
}
.brand{display:flex;align-items:center;gap:9px;color:var(--ink);font-weight:700;font-size:18px;letter-spacing:.01em}
.brand:hover{text-decoration:none}
.brand img{height:32px;width:32px;flex:none}
.brand small{display:block;font-size:10.5px;font-weight:600;color:var(--muted);letter-spacing:.06em;line-height:1.2}
.topbar-nav{display:flex;align-items:center;gap:6px}
.topbar-nav a{
  color:var(--ink-2);font-size:14px;font-weight:600;padding:7px 12px;border-radius:10px;
}
.topbar-nav a:hover{background:var(--surface-2);text-decoration:none}
.btn{
  display:inline-flex;align-items:center;justify-content:center;gap:8px;
  background:linear-gradient(180deg,var(--brand-2),var(--brand));
  color:#fff !important;font-weight:700;font-size:14.5px;
  padding:10px 18px;border-radius:12px;border:0;cursor:pointer;
  box-shadow:0 6px 18px -8px rgba(255,82,0,.75);
  transition:transform .12s ease,box-shadow .12s ease;
}
.btn:hover{text-decoration:none;transform:translateY(-1px);box-shadow:0 10px 22px -8px rgba(255,82,0,.8)}
.btn:active{transform:translateY(0)}
.btn-ghost{
  background:var(--surface);color:var(--ink) !important;
  border:1px solid var(--line);box-shadow:var(--shadow-sm);
}
.btn-ghost:hover{border-color:var(--brand-line);background:var(--surface-2)}
.btn-block{width:100%}
@media (max-width:640px){
  .topbar-nav a.hide-sm{display:none}
  .topbar-in{padding:9px 14px}
  .brand{font-size:16px}
}

/* ---------- layout ------------------------------------------------------ */
main{max-width:1000px;margin:0 auto;padding:22px 18px 64px}
.reading{max-width:790px}
@media (max-width:640px){main{padding:16px 14px 52px}}

/* ---------- breadcrumb -------------------------------------------------- */
.crumbs{
  display:flex;flex-wrap:wrap;align-items:center;gap:6px 4px;
  font-size:13.5px;color:var(--muted);margin:2px 0 18px;
}
.crumbs a{color:var(--muted);font-weight:500}
.crumbs a:hover{color:var(--brand-ink)}
.crumbs .sep{color:var(--muted-2);font-size:12px}
.crumbs .cur{color:var(--ink-2);font-weight:600;max-width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}

/* ---------- typography -------------------------------------------------- */
h1{
  font-family:var(--serif);font-weight:700;
  font-size:clamp(22px,4.6vw,33px);line-height:1.85;
  letter-spacing:.003em;margin:0 0 6px;color:var(--ink);
  text-wrap:pretty;overflow-wrap:anywhere;
}
h2{
  font-family:var(--sans);font-weight:700;
  font-size:clamp(18px,3.1vw,22px);line-height:1.5;
  margin:34px 0 12px;color:var(--ink);letter-spacing:.005em;
}
h3{font-size:16.5px;font-weight:700;margin:22px 0 8px}
p{margin:0 0 14px}
.lede{color:var(--muted);font-size:16.5px;line-height:1.9;margin:0 0 10px}
.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}

/* ---------- cards ------------------------------------------------------- */
.card{
  background:var(--surface);border:1px solid var(--line);border-radius:var(--radius);
  box-shadow:var(--shadow);
}
.qcard{padding:26px 26px 28px;margin:0 0 22px;position:relative;overflow:hidden}
.qcard::before{
  content:"";position:absolute;inset:0 0 auto 0;height:4px;
  background:linear-gradient(90deg,var(--brand),var(--brand-2) 45%,#ffb27a);
}
@media (max-width:640px){.qcard{padding:20px 17px 22px}}

/* ---------- meta chips -------------------------------------------------- */
.chips{display:flex;flex-wrap:wrap;gap:7px;margin:14px 0 4px}
.chip{
  display:inline-flex;align-items:center;gap:6px;
  background:var(--surface-2);border:1px solid var(--line);
  color:var(--ink-2);border-radius:999px;padding:4px 12px;
  font-size:13px;font-weight:600;line-height:1.6;
  transition:border-color .12s,color .12s,background .12s;
}
a.chip:hover{border-color:var(--brand-line);color:var(--brand-ink);background:var(--brand-soft);text-decoration:none}
.chip-subject{background:var(--brand-soft);border-color:var(--brand-line);color:var(--brand-ink)}
.chip-exam{background:var(--blue-soft);border-color:var(--blue-line);color:var(--blue-ink)}
.chip-level{background:var(--gold-soft);border-color:var(--gold-line);color:var(--gold-ink)}
.chip-dot{width:6px;height:6px;border-radius:50%;background:currentColor;opacity:.55}

/* ---------- question image ---------------------------------------------- */
.qimg{border-radius:var(--radius-sm);border:1px solid var(--line);margin:14px 0;background:var(--surface)}

/* ---------- options ----------------------------------------------------- */
.opts{list-style:none;margin:20px 0 0;padding:0;display:grid;gap:10px}
.opt{
  display:flex;align-items:flex-start;gap:13px;
  background:var(--surface-2);border:1px solid var(--line);
  border-radius:var(--radius-sm);padding:13px 16px 13px 13px;
  font-size:16.5px;line-height:1.8;color:var(--ink-2);
  transition:border-color .14s,background .14s,transform .14s;
}
.opt:hover{border-color:var(--muted-2)}
.opt-letter{
  flex:none;width:32px;height:32px;border-radius:10px;
  display:grid;place-items:center;
  background:var(--surface);border:1.5px solid var(--line);
  font-family:var(--sans);font-weight:700;font-size:15.5px;color:var(--ink-2);
  margin-top:3px;
}
.opt-body{flex:1;min-width:0}
.opt-body img{border-radius:10px;margin-top:8px;border:1px solid var(--line)}
.opt.correct{
  background:var(--ok-soft);border-color:var(--ok-line);
  box-shadow:inset 3px 0 0 var(--ok);
  color:var(--ink);font-weight:600;
}
.opt.correct .opt-letter{background:var(--ok);border-color:var(--ok);color:#fff}
.opt-tag{
  flex:none;align-self:center;
  font-size:11.5px;font-weight:800;letter-spacing:.04em;
  color:var(--ok-ink);background:color-mix(in srgb,var(--ok) 12%,transparent);
  border:1px solid var(--ok-line);border-radius:999px;padding:3px 9px;white-space:nowrap;
}
.opt-hint{display:block;margin-top:6px;font-size:13px;font-weight:500;color:var(--muted)}

/* ---------- answer + explanation ---------------------------------------- */
.answer{
  display:flex;align-items:flex-start;gap:13px;
  margin:22px 0 0;padding:16px 18px;
  background:var(--ok-soft);border:1px solid var(--ok-line);border-radius:var(--radius-sm);
}
.answer-mark{
  flex:none;width:30px;height:30px;border-radius:50%;
  display:grid;place-items:center;background:var(--ok);color:#fff;
  font-size:17px;font-weight:800;line-height:1;
}
.answer-body{flex:1;min-width:0}
.answer-label{
  display:block;font-size:11.5px;font-weight:800;letter-spacing:.09em;
  text-transform:uppercase;color:var(--ok-ink);margin-bottom:3px;
}
.answer-text{font-family:var(--serif);font-size:18.5px;font-weight:600;line-height:1.75;color:var(--ink);word-break:break-word}

.expl{
  margin:18px 0 0;padding:20px 20px 18px;
  background:var(--surface-2);border:1px solid var(--line);
  border-left:4px solid var(--brand);border-radius:var(--radius-sm);
}
.expl h2{
  display:flex;align-items:center;gap:9px;
  font-size:13px;font-weight:800;letter-spacing:.1em;text-transform:uppercase;
  color:var(--brand-ink);margin:0 0 10px;
}
.expl h2::before{
  content:"";width:16px;height:16px;border-radius:5px;background:var(--brand-soft);
  border:1.5px solid var(--brand-line);
}
.expl-body{font-size:16.5px;line-height:2;color:var(--ink-2);white-space:pre-wrap}
.expl-body img{border-radius:10px;margin-top:10px;border:1px solid var(--line)}
.expl-missing{
  margin:18px 0 0;padding:16px 18px;border-radius:var(--radius-sm);
  background:var(--gold-soft);border:1px dashed var(--gold-line);
  color:var(--gold-ink);font-size:15px;line-height:1.8;
}

/* ---------- actions ----------------------------------------------------- */
.actions{display:flex;flex-wrap:wrap;gap:10px;margin:22px 0 0}
.actions .btn{flex:1 1 200px}

/* ---------- meta footer -------------------------------------------------- */
.qmeta{
  display:flex;flex-wrap:wrap;gap:6px 18px;align-items:center;
  margin-top:22px;padding-top:16px;border-top:1px dashed var(--line);
  font-size:13px;color:var(--muted);
}
.qmeta b{font-weight:700;color:var(--ink-2)}
.qmeta a{color:var(--muted)}
.qmeta a:hover{color:var(--brand-ink)}

/* ---------- related list ------------------------------------------------ */
.qlist{display:grid;gap:8px;margin:12px 0 0}
.qlist a{
  display:flex;align-items:flex-start;gap:11px;
  background:var(--surface);border:1px solid var(--line);
  border-radius:var(--radius-sm);padding:12px 15px;
  color:var(--ink-2);font-size:15.5px;line-height:1.75;font-weight:500;
  transition:border-color .13s,color .13s,transform .13s;
}
.qlist a:hover{border-color:var(--brand-line);color:var(--ink);text-decoration:none;transform:translateX(2px)}
.qlist .n{
  flex:none;width:24px;height:24px;border-radius:7px;background:var(--surface-2);
  border:1px solid var(--line);display:grid;place-items:center;
  font-family:var(--latin);font-size:12px;font-weight:700;color:var(--muted);margin-top:3px;
}
.qlist .arrow{margin-left:auto;color:var(--muted-2);flex:none}
.more-link{display:inline-flex;align-items:center;gap:7px;font-weight:700;font-size:15px;margin-top:12px}

/* ---------- pager -------------------------------------------------------- */
.pager{display:flex;gap:10px;margin:26px 0 0;flex-wrap:wrap}
.pager a{
  flex:1 1 220px;display:flex;flex-direction:column;gap:3px;
  background:var(--surface);border:1px solid var(--line);border-radius:var(--radius-sm);
  padding:12px 15px;color:var(--ink-2);
}
.pager a:hover{border-color:var(--brand-line);text-decoration:none}
.pager small{font-size:11.5px;font-weight:800;letter-spacing:.08em;text-transform:uppercase;color:var(--muted)}
.pager span{font-size:14.5px;font-weight:600;line-height:1.6;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}

/* ---------- grid cards (syllabus) --------------------------------------- */
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(272px,1fr));gap:12px;margin:20px 0}
.gcard{
  display:block;background:var(--surface);border:1px solid var(--line);
  border-radius:var(--radius-sm);padding:15px 17px;color:var(--ink);
  transition:border-color .13s,transform .13s,box-shadow .13s;
}
.gcard:hover{border-color:var(--brand-line);text-decoration:none;transform:translateY(-2px);box-shadow:var(--shadow)}
.gcard b{display:block;font-size:16px;font-weight:700;margin-bottom:3px;line-height:1.6}
.gcard span{color:var(--muted);font-size:13.5px;line-height:1.7}
.gcard .count{
  display:inline-block;margin-top:8px;font-family:var(--latin);font-size:11.5px;font-weight:700;
  color:var(--brand-ink);background:var(--brand-soft);border:1px solid var(--brand-line);
  border-radius:999px;padding:2px 9px;
}

/* ---------- topics ------------------------------------------------------- */
ul.topics{margin:10px 0 0;padding-left:22px}
ul.topics li{margin:6px 0;line-height:1.85}
ul.topics ul{margin:5px 0;padding-left:19px;color:var(--muted);font-size:15.5px}

/* ---------- tips / callouts --------------------------------------------- */
.tips{
  background:var(--brand-soft);border:1px solid var(--brand-line);
  border-radius:var(--radius-sm);padding:18px 20px;margin:24px 0;
}
.tips h2{margin-top:0;color:var(--brand-ink)}
.note{
  background:var(--blue-soft);border:1px solid var(--blue-line);
  border-radius:var(--radius-sm);padding:15px 18px;margin:20px 0;
  color:var(--ink-2);font-size:15.5px;line-height:1.85;
}

/* ---------- CTA banner --------------------------------------------------- */
.banner{
  margin:34px 0 6px;border-radius:22px;padding:30px 26px;text-align:center;color:#fff;
  background:
    radial-gradient(120% 140% at 12% 0%,rgba(255,255,255,.22),transparent 55%),
    linear-gradient(135deg,#ff7a33,#ff5200 55%,#e63e00);
  box-shadow:0 20px 44px -22px rgba(255,82,0,.85);
}
.banner h2{margin:0 0 6px;color:#fff;font-size:clamp(19px,3.4vw,24px)}
.banner p{margin:0 0 18px;opacity:.95;font-size:15.5px;line-height:1.8}
.banner a{display:inline-block;background:#fff;color:#d63f00;font-weight:800;padding:12px 26px;border-radius:12px}
.banner a:hover{text-decoration:none;transform:translateY(-1px)}

/* ---------- footer -------------------------------------------------------- */
footer{border-top:1px solid var(--line);background:var(--surface);margin-top:44px}
.footer-in{max-width:1000px;margin:0 auto;padding:26px 18px;display:grid;gap:18px}
.footer-links{display:flex;flex-wrap:wrap;gap:7px 20px;font-size:14.5px}
.footer-links a{color:var(--muted);font-weight:500}
.footer-links a:hover{color:var(--brand-ink)}
.footer-bottom{
  border-top:1px solid var(--line-2);padding-top:14px;
  color:var(--muted);font-size:13.5px;line-height:1.8;
  display:flex;flex-wrap:wrap;gap:6px 16px;justify-content:space-between;
}

/* ---------- 404 ----------------------------------------------------------- */
.notfound{text-align:center;padding:60px 20px}
.notfound h1{font-size:clamp(24px,5vw,34px)}

/* ---------- MathJax ------------------------------------------------------- */
mjx-container{overflow-x:auto;overflow-y:hidden;max-width:100%;padding:2px 0}
mjx-container[display="true"]{margin:14px 0 !important}

@media print{
  .topbar,footer,.banner,.actions,.pager{display:none}
  body{background:#fff}
  .card{box-shadow:none}
}
@media (prefers-reduced-motion:reduce){
  *{transition:none !important;animation:none !important}
}
`;

/**
 * Minimal JSON-LD for the site name. Google uses `WebSite.name` (and
 * `og:site_name`) to render the brand line in search results — the same
 * mechanism that produces "- চর্চা" / "- Sattacademy" on other platforms.
 */
export const SITE_LD = {
  '@type': 'WebSite',
  '@id': `${SITE}/#website`,
  url: `${SITE}/`,
  name: BRAND,
  alternateName: [BRAND_LATIN, `${BRAND_LATIN} App`],
  inLanguage: 'bn-BD',
  publisher: { '@id': `${SITE}/#organization` },
};

export const ORG_LD = {
  '@type': ['Organization', 'EducationalOrganization'],
  '@id': `${SITE}/#organization`,
  name: BRAND,
  alternateName: [BRAND_LATIN, 'porikkhangon.app'],
  url: `${SITE}/`,
  logo: { '@type': 'ImageObject', url: `${SITE}/og-image.jpg` },
  areaServed: { '@type': 'Country', name: 'Bangladesh' },
};
