
import { Quest } from "../types";

export const MILESTONE_QUESTS: Quest[] = [
    // --- NOVICE (Level 1) ---
    {
        id: "m_exam_1",
        title: "প্রথম পদক্ষেপ",
        description: "১টি মডেল টেস্ট সম্পন্ন করো",
        type: "EXAM_COMPLETE",
        target: 1,
        progress: 0,
        reward: 50,
        completed: false,
        claimed: false,
        icon: "FileCheck",
        category: "LIFETIME",
        difficulty: "NOVICE"
    },
    {
        id: "m_study_1",
        title: "পড়ুয়া",
        description: "স্টাডি ট্র্যাকারে ১ ঘণ্টা সময় দাও",
        type: "STUDY_TIME",
        target: 60, // minutes
        progress: 0,
        reward: 50,
        completed: false,
        claimed: false,
        icon: "Clock",
        category: "LIFETIME",
        difficulty: "NOVICE"
    },
    {
        id: "m_battle_play_1",
        title: "যোদ্ধার আগমন",
        description: "১টি কুইজ ব্যাটল খেলো",
        type: "PLAY_BATTLE",
        target: 1,
        progress: 0,
        reward: 50,
        completed: false,
        claimed: false,
        icon: "Swords",
        category: "LIFETIME",
        difficulty: "NOVICE"
    },
    {
        id: "m_ai_1",
        title: "কৌতুহলী মন",
        description: "AI টিউটরকে ১টি প্রশ্ন করো",
        type: "ASK_AI",
        target: 1,
        progress: 0,
        reward: 30,
        completed: false,
        claimed: false,
        icon: "Bot",
        category: "LIFETIME",
        difficulty: "NOVICE"
    },
    {
        id: "m_save_1",
        title: "সংগ্রাহক",
        description: "১টি গুরুত্বপূর্ণ প্রশ্ন সেভ করো",
        type: "SAVE_QUESTION",
        target: 1,
        progress: 0,
        reward: 20,
        completed: false,
        claimed: false,
        icon: "Bookmark",
        category: "LIFETIME",
        difficulty: "NOVICE"
    },

    // --- APPRENTICE (Level 2) ---
    {
        id: "m_exam_5",
        title: "অনুশীলন শুরু",
        description: "৫টি মডেল টেস্ট সম্পন্ন করো",
        type: "EXAM_COMPLETE",
        target: 5,
        progress: 0,
        reward: 150,
        completed: false,
        claimed: false,
        icon: "FileCheck",
        category: "LIFETIME",
        difficulty: "APPRENTICE"
    },
    {
        id: "m_score_3",
        title: "শার্প শ্যুটার",
        description: "৩টি পরীক্ষায় ৮০% এর বেশি নম্বর পাও",
        type: "HIGH_SCORE",
        target: 3,
        progress: 0,
        reward: 200,
        completed: false,
        claimed: false,
        icon: "Target",
        category: "LIFETIME",
        difficulty: "APPRENTICE"
    },
    {
        id: "m_battle_win_1",
        title: "প্রথম জয়",
        description: "১টি কুইজ ব্যাটল জেতো",
        type: "WIN_BATTLE",
        target: 1,
        progress: 0,
        reward: 100,
        completed: false,
        claimed: false,
        icon: "Trophy",
        category: "LIFETIME",
        difficulty: "APPRENTICE"
    },
    {
        id: "m_study_10",
        title: "মনোযোগী ছাত্র",
        description: "মোট ১০ ঘণ্টা পড়াশোনা ট্র্যাক করো",
        type: "STUDY_TIME",
        target: 600,
        progress: 0,
        reward: 200,
        completed: false,
        claimed: false,
        icon: "Clock",
        category: "LIFETIME",
        difficulty: "APPRENTICE"
    },
    {
        id: "m_ai_10",
        title: "জ্ঞানপিপাসু",
        description: "AI এর সাথে ১০ বার আলোচনা করো",
        type: "ASK_AI",
        target: 10,
        progress: 0,
        reward: 100,
        completed: false,
        claimed: false,
        icon: "Bot",
        category: "LIFETIME",
        difficulty: "APPRENTICE"
    },
    {
        id: "m_mistake_5",
        title: "ভুল থেকে শিক্ষা",
        description: "৫ বার নিজের ভুলগুলো রিভিশন দাও",
        type: "VIEW_MISTAKES",
        target: 5,
        progress: 0,
        reward: 150,
        completed: false,
        claimed: false,
        icon: "Zap",
        category: "LIFETIME",
        difficulty: "APPRENTICE"
    },

    // --- ELITE (Level 3) ---
    {
        id: "m_exam_25",
        title: "এক্সাম ওয়ারিয়র",
        description: "২৫টি মডেল টেস্ট সম্পন্ন করো",
        type: "EXAM_COMPLETE",
        target: 25,
        progress: 0,
        reward: 500,
        completed: false,
        claimed: false,
        icon: "FileCheck",
        category: "LIFETIME",
        difficulty: "ELITE"
    },
    {
        id: "m_score_10",
        title: "মেধাবী",
        description: "১০টি পরীক্ষায় ৮০% এর বেশি নম্বর পাও",
        type: "HIGH_SCORE",
        target: 10,
        progress: 0,
        reward: 600,
        completed: false,
        claimed: false,
        icon: "Target",
        category: "LIFETIME",
        difficulty: "ELITE"
    },
    {
        id: "m_battle_play_25",
        title: "ব্যাটল ভেটেরান",
        description: "২৫টি কুইজ ব্যাটল খেলো",
        type: "PLAY_BATTLE",
        target: 25,
        progress: 0,
        reward: 400,
        completed: false,
        claimed: false,
        icon: "Swords",
        category: "LIFETIME",
        difficulty: "ELITE"
    },
    {
        id: "m_battle_win_10",
        title: "চ্যাম্পিয়ন",
        description: "১০টি কুইজ ব্যাটল জেতো",
        type: "WIN_BATTLE",
        target: 10,
        progress: 0,
        reward: 500,
        completed: false,
        claimed: false,
        icon: "Crown",
        category: "LIFETIME",
        difficulty: "ELITE"
    },
    {
        id: "m_study_50",
        title: "বইপোকা",
        description: "মোট ৫০ ঘণ্টা পড়াশোনা ট্র্যাক করো",
        type: "STUDY_TIME",
        target: 3000,
        progress: 0,
        reward: 600,
        completed: false,
        claimed: false,
        icon: "Clock",
        category: "LIFETIME",
        difficulty: "ELITE"
    },
    {
        id: "m_save_50",
        title: "গ্রন্থাগারিক",
        description: "৫০টি প্রশ্ন সেভ করো",
        type: "SAVE_QUESTION",
        target: 50,
        progress: 0,
        reward: 300,
        completed: false,
        claimed: false,
        icon: "Bookmark",
        category: "LIFETIME",
        difficulty: "ELITE"
    },

    // --- MASTER (Level 4) ---
    {
        id: "m_exam_50",
        title: "অদম্য",
        description: "৫০টি মডেল টেস্ট সম্পন্ন করো",
        type: "EXAM_COMPLETE",
        target: 50,
        progress: 0,
        reward: 1000,
        completed: false,
        claimed: false,
        icon: "FileCheck",
        category: "LIFETIME",
        difficulty: "MASTER"
    },
    {
        id: "m_score_25",
        title: " জিনিয়াস",
        description: "২৫টি পরীক্ষায় ৮০% এর বেশি নম্বর পাও",
        type: "HIGH_SCORE",
        target: 25,
        progress: 0,
        reward: 1200,
        completed: false,
        claimed: false,
        icon: "Star",
        category: "LIFETIME",
        difficulty: "MASTER"
    },
    {
        id: "m_battle_win_25",
        title: "অজেয়",
        description: "২৫টি কুইজ ব্যাটল জেতো",
        type: "WIN_BATTLE",
        target: 25,
        progress: 0,
        reward: 1000,
        completed: false,
        claimed: false,
        icon: "Crown",
        category: "LIFETIME",
        difficulty: "MASTER"
    },
    {
        id: "m_study_100",
        title: "স্কলার",
        description: "মোট ১০০ ঘণ্টা পড়াশোনা ট্র্যাক করো",
        type: "STUDY_TIME",
        target: 6000,
        progress: 0,
        reward: 1500,
        completed: false,
        claimed: false,
        icon: "BookOpen",
        category: "LIFETIME",
        difficulty: "MASTER"
    },
    {
        id: "m_points_5k",
        title: "পয়েন্ট টাইকুন",
        description: "মোট ৫০০০ পয়েন্ট অর্জন করো",
        type: "EARN_POINTS",
        target: 5000,
        progress: 0,
        reward: 1000,
        completed: false,
        claimed: false,
        icon: "Zap",
        category: "LIFETIME",
        difficulty: "MASTER"
    },

    // --- LEGEND (Level 5 - Hardest) ---
    {
        id: "m_exam_100",
        title: "সেঞ্চুরি ক্লাব",
        description: "১০০টি মডেল টেস্ট সম্পন্ন করো",
        type: "EXAM_COMPLETE",
        target: 100,
        progress: 0,
        reward: 2500,
        completed: false,
        claimed: false,
        icon: "Trophy",
        category: "LIFETIME",
        difficulty: "LEGEND"
    },
    {
        id: "m_exam_500",
        title: "এক্সাম মেশিন",
        description: "৫০০টি মডেল টেস্ট সম্পন্ন করো (Ultimate Challenge)",
        type: "EXAM_COMPLETE",
        target: 500,
        progress: 0,
        reward: 10000,
        completed: false,
        claimed: false,
        icon: "Trophy",
        category: "LIFETIME",
        difficulty: "LEGEND"
    },
    {
        id: "m_score_50",
        title: "পারফেকশনিস্ট",
        description: "৫০টি পরীক্ষায় ৮০% এর বেশি নম্বর পাও",
        type: "HIGH_SCORE",
        target: 50,
        progress: 0,
        reward: 3000,
        completed: false,
        claimed: false,
        icon: "Star",
        category: "LIFETIME",
        difficulty: "LEGEND"
    },
    {
        id: "m_battle_play_100",
        title: "ওয়ার লর্ড",
        description: "১০০টি কুইজ ব্যাটল খেলো",
        type: "PLAY_BATTLE",
        target: 100,
        progress: 0,
        reward: 2000,
        completed: false,
        claimed: false,
        icon: "Swords",
        category: "LIFETIME",
        difficulty: "LEGEND"
    },
    {
        id: "m_battle_win_50",
        title: "ব্যাটল লিজেন্ড",
        description: "৫০টি কুইজ ব্যাটল জেতো",
        type: "WIN_BATTLE",
        target: 50,
        progress: 0,
        reward: 5000,
        completed: false,
        claimed: false,
        icon: "Crown",
        category: "LIFETIME",
        difficulty: "LEGEND"
    },
    {
        id: "m_study_500",
        title: "গ্রান্ডমাস্টার",
        description: "মোট ৫০০ ঘণ্টা পড়াশোনা ট্র্যাক করো",
        type: "STUDY_TIME",
        target: 30000,
        progress: 0,
        reward: 5000,
        completed: false,
        claimed: false,
        icon: "BookOpen",
        category: "LIFETIME",
        difficulty: "LEGEND"
    },
    {
        id: "m_points_20k",
        title: "ধ্রুবক আইকন",
        description: "মোট ২০,০০০ পয়েন্ট অর্জন করো",
        type: "EARN_POINTS",
        target: 20000,
        progress: 0,
        reward: 5000,
        completed: false,
        claimed: false,
        icon: "Zap",
        category: "LIFETIME",
        difficulty: "LEGEND"
    }
];
