import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import { ArrowLeft, CheckCircle2, Eye, EyeOff, Timer, ChevronRight, BookOpen } from 'lucide-react';
import { fetchExamPaperQuestionsAPI, fetchQuestionsFromBankAPI } from '../services/api';
import { QuizQuestion } from '../types';
import {
  ADMISSION_CATEGORY_LABELS,
  ADMISSION_CATEGORY_ORDER,
  ADMISSION_HUB_PATH,
  ADMISSION_INSTITUTIONS,
  AdmissionInstitution,
  buildExamTag,
  findInstitutionById,
  institutionPath,
  paperPath,
  paperTitle,
  qbankPaperLink,
  sessionToBangla,
  slugToSession,
  subjectFamilyOf,
  subjectOrderFor,
  subjectToBangla,
  toBanglaDigits,
} from '../data/admissionExams';

/**
 * Public, no-auth "বিগত বছরের প্রশ্ন" viewer — the in-app twin of the static
 * SEO pages under /admission-questions/… generated by
 * scripts/generate-seo-pages.mjs.
 *
 *   /admission-questions                    hub (all institutions)
 *   /admission-questions/:inst              sessions of one institution
 *   /admission-questions/:inst/:session     the full paper, live from the DB
 *
 * Questions are fetched with the exam-session tag filter
 * (`GET /admin/questions?board=Medical '21-22`), so any paper that exists in
 * the question bank works here even before the next static build. Kept
 * `noindex`: the canonical, indexable version is the static page.
 */

const LETTERS = ['ক', 'খ', 'গ', 'ঘ', 'ঙ', 'চ'];
const SITE = 'https://www.porikkhangon.app';

const useMathJax = (dep: unknown, ref: React.RefObject<HTMLElement | null>) => {
  useEffect(() => {
    if (!dep) return;
    let tries = 0;
    const timer = window.setInterval(() => {
      const M = (window as any).MathJax;
      if (M?.typesetPromise && ref.current) {
        M.typesetPromise([ref.current]).catch(() => {});
        window.clearInterval(timer);
      } else if (++tries > 8) {
        window.clearInterval(timer);
      }
    }, 500);
    return () => window.clearInterval(timer);
  }, [dep, ref]);
};

const Shell: React.FC<{
  title: string;
  canonical: string;
  crumbs: { label: string; to?: string }[];
  children: React.ReactNode;
}> = ({ title, canonical, crumbs, children }) => (
  <div className="pk-landing dash relative w-full min-h-[80vh] overflow-hidden bg-paper dark:bg-ink text-ink dark:text-paper">
    <Helmet>
      <title>{title}</title>
      <meta name="robots" content="noindex, follow" />
      <link rel="canonical" href={canonical} />
    </Helmet>
    <div aria-hidden className="pointer-events-none absolute inset-x-0 top-0 h-72 bg-[radial-gradient(60%_60%_at_50%_0%,rgba(255,82,0,0.09),transparent)] blur-2xl" />
    <div aria-hidden className="pointer-events-none absolute -top-20 -right-24 w-72 h-72 bg-[radial-gradient(closest-side,rgba(255,185,46,0.14),transparent)] blur-3xl" />
    <div aria-hidden className="pointer-events-none absolute inset-0 bg-[radial-gradient(rgba(22,18,16,0.04)_1px,transparent_1px)] dark:bg-[radial-gradient(rgba(255,255,255,0.05)_1px,transparent_1px)] [background-size:22px_22px]" />

    <header className="relative z-20 bg-ink shadow-[0_10px_30px_-18px_rgba(22,18,16,0.6)]">
      <div className="max-w-4xl mx-auto px-4 py-3 flex items-center justify-between gap-3">
        <Link to="/" className="flex items-center gap-2.5 text-paper font-bold text-[17px]">
          <span className="w-8 h-8 rounded-xl ring-conic grid place-items-center text-white font-extrabold shadow-md">প</span>
          পরীক্ষাঙ্গন
        </Link>
        <Link
          to="/auth"
          className="bg-lime text-ink font-extrabold text-sm px-4 py-2 rounded-full shadow-[0_10px_24px_-10px_rgba(255,185,46,0.6)] transition-transform hover:-translate-y-0.5"
        >
          ফ্রি শুরু করো
        </Link>
      </div>
    </header>

    <div className="max-w-4xl mx-auto relative z-10 py-7 px-4">
      <nav aria-label="breadcrumb" className="flex flex-wrap items-center gap-1.5 text-[13px] font-semibold text-mist mb-5">
        {crumbs.map((c, i) => (
          <React.Fragment key={i}>
            {i > 0 && <ChevronRight size={14} className="text-ink/25 dark:text-white/25" />}
            {c.to ? (
              <Link to={c.to} className="hover:text-brand-deep dark:hover:text-brand-bright transition-colors">
                {c.label}
              </Link>
            ) : (
              <span className="text-ink dark:text-paper">{c.label}</span>
            )}
          </React.Fragment>
        ))}
      </nav>
      {children}
    </div>
  </div>
);

const Spinner: React.FC<{ label: string }> = ({ label }) => (
  <div className="flex flex-col items-center justify-center py-24 text-mist">
    <div className="w-10 h-10 border-4 border-brand border-t-transparent rounded-full animate-spin mb-4" />
    <p className="text-sm font-bold">{label}</p>
  </div>
);

const PageTitle: React.FC<{ children: React.ReactNode; sub?: React.ReactNode }> = ({ children, sub }) => (
  <div className="mb-6">
    <h1 className="font-bangla text-2xl md:text-[34px] font-extrabold leading-snug tracking-tight text-ink dark:text-paper after:content-[''] after:block after:w-[76px] after:h-[5px] after:rounded-full after:mt-4 after:bg-gradient-to-r after:from-brand after:to-lime">
      {children}
    </h1>
    {sub && <p className="mt-3 text-[15px] text-mist leading-relaxed">{sub}</p>}
  </div>
);

// ---------------------------------------------------------------------------
// Hub: all institutions
// ---------------------------------------------------------------------------
const HubView: React.FC = () => (
  <Shell
    title="বিগত বছরের ভর্তি পরীক্ষার প্রশ্ন ও সমাধান | পরীক্ষাঙ্গন"
    canonical={`${SITE}${ADMISSION_HUB_PATH}`}
    crumbs={[{ label: 'পরীক্ষাঙ্গন', to: '/' }, { label: 'বিগত বছরের ভর্তি প্রশ্ন' }]}
  >
    <PageTitle sub="মেডিকেল, ডেন্টাল, ঢাবি, বুয়েট, GST সহ প্রধান ভর্তি পরীক্ষাগুলোর বিগত বছরের প্রশ্নপত্র — সঠিক উত্তর ও ব্যাখ্যাসহ, সরাসরি প্রশ্নব্যাংক থেকে।">
      বিগত বছরের ভর্তি পরীক্ষার প্রশ্ন ও সমাধান
    </PageTitle>
    {ADMISSION_CATEGORY_ORDER.map((cat) => {
      const list = ADMISSION_INSTITUTIONS.filter((i) => i.category === cat);
      if (!list.length) return null;
      return (
        <section key={cat} className="mb-8">
          <h2 className="font-bangla text-lg font-bold mb-3 text-ink dark:text-paper">{ADMISSION_CATEGORY_LABELS[cat]}</h2>
          <div className="grid sm:grid-cols-2 gap-3">
            {list.map((inst) => (
              <Link
                key={inst.id}
                to={institutionPath(inst)}
                className="group bg-white dark:bg-ink-2 ring-1 ring-ink/10 dark:ring-white/10 rounded-2xl p-4 hover:ring-brand/40 hover:-translate-y-0.5 transition-all shadow-[0_1px_2px_rgba(22,18,16,0.04)]"
              >
                <b className="block text-[15.5px] text-ink dark:text-paper group-hover:text-brand-deep dark:group-hover:text-brand-bright">{inst.name}</b>
                <span className="text-xs text-mist font-semibold">{inst.nameEn} · সব সেশন</span>
              </Link>
            ))}
          </div>
        </section>
      );
    })}
  </Shell>
);

// ---------------------------------------------------------------------------
// Institution: discover sessions live (one cheap probe per session)
// ---------------------------------------------------------------------------
const candidateSessions = () => {
  const y = new Date().getFullYear();
  return Array.from({ length: 13 }, (_, i) => {
    const start = y - i;
    return `${String(start).slice(2)}-${String(start + 1).slice(2)}`;
  });
};

const InstitutionView: React.FC<{ inst: AdmissionInstitution }> = ({ inst }) => {
  const [sessions, setSessions] = useState<{ session: string; total: number }[] | null>(null);

  useEffect(() => {
    let cancelled = false;
    setSessions(null);
    (async () => {
      const found = await Promise.all(
        candidateSessions().map(async (session) => {
          try {
            const res = await fetchQuestionsFromBankAPI(1, 1, undefined, undefined, undefined, undefined, undefined, undefined, buildExamTag(inst.tag, session));
            return { session, total: Number(res?.total) || 0 };
          } catch {
            return { session, total: 0 };
          }
        })
      );
      if (!cancelled) setSessions(found.filter((s) => s.total > 0));
    })();
    return () => {
      cancelled = true;
    };
  }, [inst]);

  return (
    <Shell
      title={`${inst.name} — বিগত বছরের প্রশ্ন ও সমাধান | পরীক্ষাঙ্গন`}
      canonical={`${SITE}${institutionPath(inst)}`}
      crumbs={[{ label: 'পরীক্ষাঙ্গন', to: '/' }, { label: 'বিগত বছরের ভর্তি প্রশ্ন', to: ADMISSION_HUB_PATH }, { label: inst.name }]}
    >
      <PageTitle sub={inst.description}>{inst.name} — বিগত বছরের প্রশ্ন ও সমাধান</PageTitle>

      {sessions === null && <Spinner label="সেশন খোঁজা হচ্ছে…" />}
      {sessions && sessions.length === 0 && (
        <div className="bg-white dark:bg-ink-2 ring-1 ring-ink/10 dark:ring-white/10 rounded-[26px] p-8 text-center">
          <p className="text-sm text-mist">এই পরীক্ষার কোনো সেশনের প্রশ্ন এখনো প্রশ্নব্যাংকে যোগ হয়নি।</p>
          <Link to={ADMISSION_HUB_PATH} className="inline-block mt-4 text-sm font-bold text-brand-deep dark:text-brand-bright">
            অন্য পরীক্ষা দেখো →
          </Link>
        </div>
      )}
      {sessions && sessions.length > 0 && (
        <div className="grid sm:grid-cols-2 gap-3">
          {sessions.map(({ session, total }) => (
            <Link
              key={session}
              to={paperPath(inst, session)}
              className="group bg-white dark:bg-ink-2 ring-1 ring-ink/10 dark:ring-white/10 rounded-2xl p-4 hover:ring-brand/40 hover:-translate-y-0.5 transition-all"
            >
              <span className="font-bangla text-xl font-extrabold text-brand-deep dark:text-brand-bright">{sessionToBangla(session)}</span>
              <b className="block text-[15px] text-ink dark:text-paper group-hover:text-brand-deep dark:group-hover:text-brand-bright">
                {paperTitle(inst, session)} — প্রশ্ন ও সমাধান
              </b>
              <span className="text-xs text-mist font-semibold">{toBanglaDigits(total)}টি প্রশ্ন · উত্তর ও ব্যাখ্যাসহ</span>
            </Link>
          ))}
        </div>
      )}

      {inst.format && (
        <div className="mt-8 bg-white dark:bg-ink-2 ring-1 ring-ink/10 dark:ring-white/10 rounded-2xl overflow-hidden">
          <h2 className="font-bangla text-base font-bold px-4 py-3 bg-cream dark:bg-white/5 text-ink dark:text-paper">পরীক্ষার ধরন</h2>
          <dl className="divide-y divide-ink/10 dark:divide-white/10 text-sm">
            {inst.format.map((r) => (
              <div key={r.label} className="grid grid-cols-[38%_1fr] gap-3 px-4 py-2.5">
                <dt className="font-bold text-brand-deep dark:text-brand-bright">{r.label}</dt>
                <dd className="text-ink/80 dark:text-white/80">{r.value}</dd>
              </div>
            ))}
          </dl>
        </div>
      )}
    </Shell>
  );
};

// ---------------------------------------------------------------------------
// Paper: the full question set of one session
// ---------------------------------------------------------------------------
const PaperView: React.FC<{ inst: AdmissionInstitution; session: string }> = ({ inst, session }) => {
  const tag = buildExamTag(inst.tag, session);
  const title = paperTitle(inst, session);
  const [questions, setQuestions] = useState<QuizQuestion[] | null>(null);
  const [failed, setFailed] = useState(false);
  const [hideAnswers, setHideAnswers] = useState(false);
  const [picked, setPicked] = useState<Record<string, number>>({});
  const bodyRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    let cancelled = false;
    setQuestions(null);
    setFailed(false);
    setPicked({});
    fetchExamPaperQuestionsAPI(tag)
      .then((res) => {
        if (cancelled) return;
        const famOrder = subjectOrderFor(inst);
        const rank = (q: QuizQuestion) => {
          const i = famOrder.indexOf(subjectFamilyOf(q.subject || '').key);
          return i === -1 ? 99 : i;
        };
        const created = (q: QuizQuestion) => Number((q as QuizQuestion & { createdAt?: number }).createdAt) || 0;
        const sorted = res.questions
          .map((q, i) => ({ q, i }))
          .sort(
            ({ q: a, i: ia }, { q: b, i: ib }) =>
              rank(a) - rank(b) ||
              (a.subject || '').localeCompare(b.subject || '') ||
              created(a) - created(b) ||
              (a.orderIndex || 0) - (b.orderIndex || 0) ||
              ia - ib
          )
          .map(({ q }) => q);
        setQuestions(sorted);
      })
      .catch(() => !cancelled && setFailed(true));
    return () => {
      cancelled = true;
    };
  }, [tag, inst]);

  useMathJax(questions, bodyRef);

  const groups = useMemo(() => {
    const map = new Map<string, { key: string; bn: string; en: string; items: QuizQuestion[] }>();
    for (const q of questions || []) {
      const f = subjectFamilyOf(q.subject || '');
      if (!map.has(f.key)) map.set(f.key, { ...f, items: [] });
      map.get(f.key)!.items.push(q);
    }
    return [...map.values()];
  }, [questions]);

  const explained = (questions || []).filter((q) => q.explanation).length;
  let serial = 0;

  return (
    <Shell
      title={`${title} প্রশ্ন ও সমাধান | পরীক্ষাঙ্গন`}
      canonical={`${SITE}${paperPath(inst, session)}`}
      crumbs={[
        { label: 'পরীক্ষাঙ্গন', to: '/' },
        { label: 'বিগত বছরের ভর্তি প্রশ্ন', to: ADMISSION_HUB_PATH },
        { label: inst.name, to: institutionPath(inst) },
        { label: sessionToBangla(session) },
      ]}
    >
      <div className="flex items-center justify-between mb-4">
        <Link to={institutionPath(inst)} className="focus-ring flex items-center gap-2 text-sm font-bold text-mist hover:text-brand-deep dark:hover:text-brand-bright transition-colors">
          <ArrowLeft size={16} /> সব সেশন
        </Link>
      </div>

      <PageTitle
        sub={
          questions
            ? `${title} সেশনের ${toBanglaDigits(questions.length)}টি প্রশ্ন — সঠিক উত্তর${explained ? ` ও ${toBanglaDigits(explained)}টি ব্যাখ্যাসহ` : ''}, বিষয় অনুযায়ী সাজানো। উত্তর লুকিয়ে নিজে সলভ করো, তারপর মিলিয়ে নাও।`
            : undefined
        }
      >
        {title} — প্রশ্ন ও সমাধান
      </PageTitle>

      {questions === null && !failed && <Spinner label="প্রশ্নপত্র লোড হচ্ছে…" />}

      {(failed || (questions && questions.length === 0)) && (
        <div className="bg-white dark:bg-ink-2 ring-1 ring-ink/10 dark:ring-white/10 rounded-[26px] p-8 text-center">
          <h2 className="font-bangla text-lg font-extrabold mb-2">এই সেশনের প্রশ্ন পাওয়া যায়নি</h2>
          <p className="text-sm text-mist mb-5">{tag} ট্যাগে এখনো কোনো প্রশ্ন প্রশ্নব্যাংকে নেই, অথবা সার্ভারে সাময়িক সমস্যা হচ্ছে।</p>
          <Link to={institutionPath(inst)} className="focus-ring inline-block px-5 py-2.5 bg-brand hover:bg-brand-deep text-white text-sm font-bold rounded-full transition-all">
            অন্য সেশন দেখো
          </Link>
        </div>
      )}

      {questions && questions.length > 0 && (
        <div ref={bodyRef}>
          {/* Sticky toolbar */}
          <div className="sticky top-2 z-20 mb-4 flex flex-wrap items-center justify-between gap-2 rounded-2xl bg-white/85 dark:bg-ink-2/85 backdrop-blur-md ring-1 ring-ink/10 dark:ring-white/10 px-3.5 py-2.5 shadow-[0_12px_30px_-20px_rgba(22,18,16,0.35)]">
            <div className="flex flex-wrap gap-1.5">
              {groups.map((g) => (
                <a key={g.key} href={`#pq-${g.key.replace(/\s+/g, '-').toLowerCase()}`} className="text-xs font-bold px-3 py-1.5 rounded-full bg-mint text-brand-deep dark:bg-brand/20 dark:text-brand-bright">
                  {g.bn} <span className="opacity-70">{toBanglaDigits(g.items.length)}</span>
                </a>
              ))}
            </div>
            <div className="flex gap-2">
              <button
                type="button"
                onClick={() => setHideAnswers((v) => !v)}
                aria-pressed={hideAnswers}
                className="focus-ring flex items-center gap-1.5 text-xs font-bold px-3.5 py-2 rounded-full ring-1 ring-ink/15 dark:ring-white/20 bg-white dark:bg-white/5 text-ink dark:text-paper hover:ring-brand/40 transition-all"
              >
                {hideAnswers ? <Eye size={14} /> : <EyeOff size={14} />} {hideAnswers ? 'উত্তর দেখাও' : 'উত্তর লুকাও'}
              </button>
              <Link
                to={qbankPaperLink(inst, session)}
                className="focus-ring flex items-center gap-1.5 text-xs font-bold px-3.5 py-2 rounded-full bg-ink dark:bg-lime text-paper dark:text-ink hover:bg-brand-deep dark:hover:bg-gold transition-all"
              >
                <Timer size={14} /> টাইমার সহ পরীক্ষা
              </Link>
            </div>
          </div>

          {groups.map((g) => (
            <section key={g.key} id={`pq-${g.key.replace(/\s+/g, '-').toLowerCase()}`} className="scroll-mt-24 mb-8">
              <h2 className="font-bangla text-lg md:text-xl font-bold mt-6 mb-3 flex items-center gap-2.5 text-ink dark:text-paper">
                <span className="w-2.5 h-2.5 rotate-45 rounded-[3px] bg-gradient-to-br from-brand to-lime" />
                {g.bn}
                <span className="text-xs font-semibold text-mist bg-white dark:bg-white/5 ring-1 ring-ink/10 dark:ring-white/10 rounded-full px-3 py-0.5">
                  {g.en} · {toBanglaDigits(g.items.length)}টি প্রশ্ন
                </span>
              </h2>

              <div className="space-y-3">
                {g.items.map((q) => {
                  serial++;
                  const key = q._id || q.id || String(serial);
                  const chosen = picked[key];
                  const showAnswer = !hideAnswers || chosen !== undefined;
                  return (
                    <article key={key} className="bg-white dark:bg-ink-2 ring-1 ring-ink/10 dark:ring-white/10 rounded-[22px] p-4 md:p-5">
                      <div className="flex items-center gap-2.5 mb-2 flex-wrap">
                        <span className="min-w-[34px] h-[34px] px-2.5 rounded-xl bg-ink dark:bg-lime text-paper dark:text-ink font-extrabold text-sm grid place-items-center">
                          {toBanglaDigits(serial)}
                        </span>
                        <span className="text-xs font-semibold text-mist">
                          {[subjectToBangla(q.subject || ''), q.chapter].filter(Boolean).join(' · ')}
                        </span>
                      </div>
                      <h3 className="text-[16.5px] md:text-[17.5px] font-bold leading-relaxed text-ink dark:text-paper mb-2">
                        {q.slug ? (
                          <Link to={`/q/${q.slug}`} className="hover:text-brand-deep dark:hover:text-brand-bright">
                            {q.question}
                          </Link>
                        ) : (
                          q.question
                        )}
                      </h3>
                      {q.questionImage && <img src={q.questionImage} alt="প্রশ্নের চিত্র" loading="lazy" className="max-w-full rounded-xl mb-3" />}

                      <div className="grid sm:grid-cols-2 gap-2 mb-2.5">
                        {(q.options || []).map((opt, i) => {
                          const isCorrect = i === q.correctAnswerIndex;
                          const isPicked = chosen === i;
                          const tone =
                            showAnswer && isCorrect
                              ? 'border-green-500/50 bg-green-50 dark:bg-green-950/40 font-bold text-green-800 dark:text-green-300'
                              : isPicked
                                ? 'border-red-400 bg-red-50 dark:bg-red-950/30'
                                : 'border-ink/10 dark:border-white/10 bg-paper dark:bg-white/5 text-ink/85 dark:text-white/85 hover:border-brand/40';
                          return (
                            <button
                              type="button"
                              key={i}
                              disabled={!hideAnswers}
                              onClick={() => setPicked((p) => ({ ...p, [key]: i }))}
                              className={`flex items-start gap-2.5 rounded-2xl border px-3 py-2.5 text-left text-[15px] transition-colors disabled:cursor-default ${tone}`}
                            >
                              <span className={`w-7 h-7 rounded-lg grid place-items-center font-bold shrink-0 text-sm ${showAnswer && isCorrect ? 'bg-green-600 text-white' : 'bg-mint text-brand-deep dark:bg-white/10 dark:text-brand-bright'}`}>
                                {LETTERS[i]}
                              </span>
                              <span className="flex-1">
                                {opt}
                                {q.optionsImages?.[i] && <img src={q.optionsImages[i]} alt={`বিকল্প ${LETTERS[i]}`} loading="lazy" className="max-w-full rounded-lg mt-1.5" />}
                              </span>
                              {showAnswer && isCorrect && <CheckCircle2 size={16} className="text-green-600 shrink-0 mt-1" />}
                            </button>
                          );
                        })}
                      </div>

                      {showAnswer && (
                        <>
                          <div className="flex items-center gap-2.5 rounded-xl border border-green-200 dark:border-green-900 bg-green-50 dark:bg-green-950/30 px-3 py-2 text-sm">
                            <span className="w-7 h-7 rounded-full bg-green-600 text-white grid place-items-center font-extrabold">✓</span>
                            <span>
                              <b className="text-green-700 dark:text-green-400">সঠিক উত্তর:</b> {LETTERS[q.correctAnswerIndex]}. {q.options?.[q.correctAnswerIndex]}
                            </span>
                          </div>
                          {(q.explanation || q.explanationImage) && (
                            <details className="mt-2 rounded-xl border border-brand/15 dark:border-white/10 border-l-4 border-l-brand bg-cream dark:bg-white/5">
                              <summary className="cursor-pointer px-3.5 py-2.5 text-sm font-bold text-brand-deep dark:text-brand-bright">ব্যাখ্যা</summary>
                              <div className="px-3.5 pb-3 text-sm text-ink/75 dark:text-white/75 whitespace-pre-wrap leading-relaxed">
                                {q.explanation}
                                {q.explanationImage && <img src={q.explanationImage} alt="ব্যাখ্যার চিত্র" loading="lazy" className="max-w-full rounded-lg mt-2" />}
                              </div>
                            </details>
                          )}
                        </>
                      )}
                    </article>
                  );
                })}
              </div>
            </section>
          ))}

          <div className="mt-8 relative overflow-hidden rounded-[28px] bg-ink text-paper p-7 text-center">
            <div aria-hidden className="absolute -right-20 -top-20 w-72 h-72 rounded-full bg-[conic-gradient(from_120deg,rgba(255,82,0,0),rgba(255,82,0,0.55),rgba(255,185,46,0.4),rgba(255,82,0,0))] blur-3xl" />
            <h2 className="relative font-bangla text-xl font-extrabold text-lime mb-2">{title} — টাইমার সহ পুরো পরীক্ষা দাও</h2>
            <p className="relative text-sm text-white/70 mb-5">রেজাল্ট, ভুলের তালিকা ও ব্যাখ্যা সাথে সাথে — ফ্রি।</p>
            <Link to={qbankPaperLink(inst, session)} className="relative inline-flex items-center gap-2 bg-lime text-ink font-extrabold px-6 py-3 rounded-full shadow-[0_16px_36px_-14px_rgba(255,185,46,0.6)] hover:-translate-y-0.5 transition-transform">
              <BookOpen size={16} /> পরীক্ষা শুরু করো
            </Link>
          </div>
        </div>
      )}
    </Shell>
  );
};

// ---------------------------------------------------------------------------
const PastPaperPage: React.FC = () => {
  const { inst: instId = '', session: sessionSlug = '' } = useParams<{ inst?: string; session?: string }>();
  const inst = instId ? findInstitutionById(instId) : undefined;
  const session = sessionSlug ? slugToSession(sessionSlug) : null;

  if (!instId) return <HubView />;
  if (!inst || (sessionSlug && !session)) {
    return (
      <Shell title="পেজ পাওয়া যায়নি | পরীক্ষাঙ্গন" canonical={`${SITE}${ADMISSION_HUB_PATH}`} crumbs={[{ label: 'পরীক্ষাঙ্গন', to: '/' }, { label: 'বিগত বছরের ভর্তি প্রশ্ন', to: ADMISSION_HUB_PATH }]}>
        <div className="bg-white dark:bg-ink-2 ring-1 ring-ink/10 dark:ring-white/10 rounded-[26px] p-8 text-center">
          <h1 className="font-bangla text-xl font-extrabold mb-2">এই পরীক্ষাটি খুঁজে পাওয়া যায়নি</h1>
          <p className="text-sm text-mist mb-5">লিংকটি ভুল হতে পারে। নিচ থেকে পরীক্ষা বেছে নাও।</p>
          <Link to={ADMISSION_HUB_PATH} className="focus-ring inline-block px-5 py-2.5 bg-brand hover:bg-brand-deep text-white text-sm font-bold rounded-full transition-all">
            সব ভর্তি পরীক্ষা
          </Link>
        </div>
      </Shell>
    );
  }
  if (session) return <PaperView inst={inst} session={session} />;
  return <InstitutionView inst={inst} />;
};

export default PastPaperPage;
