import React, { useEffect, useMemo, useRef, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import { ArrowLeft, Check, ChevronRight, Share2, BookOpen, Sparkles, Home } from 'lucide-react';
import { fetchQuestionsFromBankAPI } from '../services/api';
import { QuizQuestion } from '../types';

/**
 * Public, no-auth question viewer.
 *
 * Revives the old (dead) share links  /#/question/<slug-or-id>  and acts as
 * the in-app counterpart of the SEO question pages at /q/<slug>/ (generated by
 * scripts/generate-seo-pages.mjs, or server-rendered by seo/ssr-server.mjs).
 *
 * Kept `noindex` on purpose: the indexable canonical version of a question is
 * its /q/<slug>/ page; this route exists so that every shared link resolves
 * inside the app. The markup below deliberately mirrors seo/render.mjs so a
 * question looks the same whichever surface the student lands on.
 */

const LETTERS = ['ক', 'খ', 'গ', 'ঘ', 'ঙ', 'চ'];

function bnSlug(text: string) {
  return String(text)
    .normalize('NFC')
    .replace(/[\u200B-\u200D\uFEFF]/g, '')
    .replace(/\\[a-zA-Z]+/g, ' ')
    .replace(/[$^_{}~\\]/g, ' ')
    .replace(/[()[\]<>«»"'`.,;:!?!…।,]/g, ' ')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 70);
}

const LEVEL_LABEL: Record<string, string> = {
  ADMISSION: 'ভর্তি পরীক্ষা',
  MAINBOOK: 'মূল বই',
  ACADEMIC: 'HSC একাডেমিক',
  PUBLIC: 'পাবলিক পরীক্ষা',
};

const QuestionPage: React.FC = () => {
  const { slug = '' } = useParams<{ slug: string }>();
  const [question, setQuestion] = useState<QuizQuestion | null>(null);
  const [related, setRelated] = useState<QuizQuestion[]>([]);
  const [state, setState] = useState<'loading' | 'ready' | 'notfound'>('loading');
  const bodyRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    let cancelled = false;
    setState('loading');
    setQuestion(null);
    setRelated([]);

    const matches = (q: QuizQuestion) =>
      q.slug === slug || bnSlug(q.question) === slug || (q as any)._id === slug || q.id === slug;

    const tryFetch = async (search: string, extra?: string) => {
      const res = await fetchQuestionsFromBankAPI(1, 30, undefined, undefined, undefined, undefined, search, undefined, undefined, undefined, undefined, undefined);
      void extra;
      return (res?.questions || []) as QuizQuestion[];
    };

    (async () => {
      try {
        // slug is a dashed form of the question text → text search narrows it down
        let list = await tryFetch(slug.replace(/-/g, ' '));
        let found = list.find(matches);
        if (!found && slug.includes('-')) {
          list = await tryFetch(slug);
          found = list.find(matches);
        }
        if (cancelled) return;
        if (found) {
          setQuestion(found);
          setState('ready');
          // Same-chapter siblings → internal links + a way onward
          try {
            const res = await fetchQuestionsFromBankAPI(1, 9, found.subject, found.chapter);
            const sibs = ((res?.questions || []) as QuizQuestion[]).filter((q) => q.id !== found!.id);
            if (!cancelled) setRelated(sibs);
          } catch {
            /* related is best-effort */
          }
        } else {
          setState('notfound');
        }
      } catch {
        if (!cancelled) setState('notfound');
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [slug]);

  // Typeset TeX once content is in the DOM (MathJax is lazy-loaded app-wide)
  useEffect(() => {
    if (state !== 'ready') return;
    let tries = 0;
    const timer = window.setInterval(() => {
      const M = (window as any).MathJax;
      if (M?.typesetPromise && bodyRef.current) {
        M.typesetPromise([bodyRef.current]).catch(() => {});
        window.clearInterval(timer);
      } else if (++tries > 8) {
        window.clearInterval(timer);
      }
    }, 500);
    return () => window.clearInterval(timer);
  }, [state]);

  const shareUrl = useMemo(
    () => `${window.location.origin}/q/${question?.slug || slug}/`,
    [question, slug]
  );

  const handleShare = () => {
    if (navigator.share) {
      navigator.share({ title: question?.question || 'পরীক্ষাঙ্গন', url: shareUrl }).catch(() => {});
    } else {
      navigator.clipboard?.writeText(shareUrl).catch(() => {});
    }
  };

  const qbankHref = question
    ? `/qbank?level=${encodeURIComponent(question.level || 'ACADEMIC')}&subject=${encodeURIComponent(question.subject || '')}&chapter=${encodeURIComponent(question.chapter || '')}`
    : '/qbank';

  return (
    <div className="w-full min-h-[80vh] bg-slate-50 dark:bg-gray-950 py-6 px-4">
      <Helmet>
        <title>{question ? `${question.question.slice(0, 60)} | পরীক্ষাঙ্গন` : 'প্রশ্ন | পরীক্ষাঙ্গন'}</title>
        <meta name="robots" content="noindex, follow" />
      </Helmet>

      <div className="max-w-3xl mx-auto">
        {/* breadcrumb */}
        <nav className="flex flex-wrap items-center gap-1.5 text-[13px] text-gray-500 dark:text-gray-400 mb-4">
          <Link to="/" className="hover:text-primary flex items-center gap-1">
            <Home size={13} /> হোম
          </Link>
          <ChevronRight size={13} className="text-gray-300 dark:text-gray-600" />
          <Link to="/qbank" className="hover:text-primary">
            প্রশ্নব্যাংক
          </Link>
          {question?.subject && (
            <>
              <ChevronRight size={13} className="text-gray-300 dark:text-gray-600" />
              <Link
                to={`/qbank?subject=${encodeURIComponent(question.subject)}`}
                className="hover:text-primary"
              >
                {question.subject}
              </Link>
            </>
          )}
          {question?.chapter && (
            <>
              <ChevronRight size={13} className="text-gray-300 dark:text-gray-600" />
              <span className="text-gray-700 dark:text-gray-300 font-semibold">{question.chapter}</span>
            </>
          )}
        </nav>

        <div className="flex items-center justify-between mb-4">
          <Link
            to="/qbank"
            className="flex items-center gap-2 text-sm font-semibold text-gray-600 dark:text-gray-300 hover:text-primary dark:hover:text-orange-400"
          >
            <ArrowLeft size={16} /> প্রশ্নব্যাংকে ফিরে যাও
          </Link>
          <button
            onClick={handleShare}
            className="flex items-center gap-2 text-sm font-semibold text-gray-600 dark:text-gray-300 hover:text-primary dark:hover:text-orange-400"
          >
            <Share2 size={16} /> শেয়ার
          </button>
        </div>

        {state === 'loading' && (
          <div className="flex flex-col items-center justify-center py-24 text-gray-400">
            <div className="w-10 h-10 border-4 border-orange-500 border-t-transparent rounded-full animate-spin mb-4" />
            <p className="text-sm font-semibold">প্রশ্ন লোড হচ্ছে…</p>
          </div>
        )}

        {state === 'notfound' && (
          <div className="bg-white dark:bg-zinc-900 border border-gray-200 dark:border-zinc-800 rounded-2xl p-8 text-center shadow-sm">
            <h1 className="text-xl font-bold text-gray-900 dark:text-white mb-2">প্রশ্নটি খুঁজে পাওয়া যায়নি</h1>
            <p className="text-sm text-gray-500 dark:text-gray-400 mb-6">
              লিংকটি পুরনো বা প্রশ্নটি মুছে ফেলা হয়ে থাকতে পারে। প্রশ্নব্যাংকে সার্চ করে দেখো।
            </p>
            <div className="flex justify-center gap-3">
              <Link to="/qbank" className="px-5 py-2.5 bg-primary hover:bg-orange-600 text-white text-sm font-bold rounded-xl">
                প্রশ্নব্যাংক খোলো
              </Link>
              <a href="/hsc-syllabus/" className="px-5 py-2.5 border border-gray-200 dark:border-zinc-700 text-sm font-bold rounded-xl text-gray-700 dark:text-gray-200">
                সিলেবাস গাইড
              </a>
            </div>
          </div>
        )}

        {state === 'ready' && question && (
          <div ref={bodyRef} className="space-y-5">
            {/* ---- question card ---- */}
            <article className="relative overflow-hidden bg-white dark:bg-zinc-900 border border-gray-200 dark:border-zinc-800 rounded-2xl p-5 md:p-8 shadow-sm">
              <span className="absolute inset-x-0 top-0 h-1 bg-gradient-to-r from-orange-500 via-orange-400 to-amber-300" />

              <div className="flex flex-wrap gap-2 mb-4">
                {question.subject && (
                  <Link
                    to={`/qbank?subject=${encodeURIComponent(question.subject)}`}
                    className="text-xs font-bold px-3 py-1 rounded-full bg-orange-50 dark:bg-orange-950 text-orange-700 dark:text-orange-300 border border-orange-200 dark:border-orange-900"
                  >
                    {question.subject}
                  </Link>
                )}
                {question.chapter && (
                  <Link
                    to={`/qbank?subject=${encodeURIComponent(question.subject || '')}&chapter=${encodeURIComponent(question.chapter)}`}
                    className="text-xs font-bold px-3 py-1 rounded-full bg-slate-50 dark:bg-zinc-800 text-gray-600 dark:text-gray-300 border border-gray-200 dark:border-zinc-700"
                  >
                    {question.chapter}
                  </Link>
                )}
                {(LEVEL_LABEL[question.level || ''] || question.level) && (
                  <span className="text-xs font-bold px-3 py-1 rounded-full bg-amber-50 dark:bg-amber-950 text-amber-700 dark:text-amber-300 border border-amber-200 dark:border-amber-900">
                    {LEVEL_LABEL[question.level || ''] || question.level}
                  </span>
                )}
                {(question.tags || []).slice(0, 3).map((t) => (
                  <span
                    key={t}
                    className="text-xs font-bold px-3 py-1 rounded-full bg-blue-50 dark:bg-blue-950 text-blue-700 dark:text-blue-300 border border-blue-200 dark:border-blue-900"
                  >
                    {t}
                  </span>
                ))}
              </div>

              <h1 className="font-serif-bn text-[22px] md:text-[30px] font-bold text-gray-900 dark:text-white leading-[1.85] mb-4">
                {question.question}
              </h1>
              {question.questionImage && (
                <img src={question.questionImage} alt="প্রশ্নের চিত্র" className="max-w-full rounded-xl mb-4 border border-gray-200 dark:border-zinc-700" />
              )}

              <div className="grid gap-2.5 mb-1">
                {(question.options || []).map((opt, i) => {
                  const isCorrect = i === question.correctAnswerIndex;
                  return (
                    <div
                      key={i}
                      className={[
                        'flex items-start gap-3 rounded-xl border px-3.5 py-3 text-[16px] md:text-[17px] leading-[1.8]',
                        isCorrect
                          ? 'border-green-300 dark:border-green-800 bg-green-50 dark:bg-green-950/40 shadow-[inset_3px_0_0_0_theme(colors.green.500)]'
                          : 'border-gray-200 dark:border-zinc-700 bg-slate-50/60 dark:bg-zinc-800/40',
                      ].join(' ')}
                    >
                      <span
                        className={[
                          'shrink-0 w-8 h-8 grid place-items-center rounded-[10px] text-[15px] font-bold mt-0.5 border',
                          isCorrect
                            ? 'bg-green-500 border-green-500 text-white'
                            : 'bg-white dark:bg-zinc-900 border-gray-200 dark:border-zinc-700 text-gray-600 dark:text-gray-300',
                        ].join(' ')}
                      >
                        {LETTERS[i]}
                      </span>
                      <span className="flex-1 min-w-0 text-gray-800 dark:text-gray-200">
                        {opt}
                        {question.optionsImages?.[i] && (
                          <img
                            src={question.optionsImages[i]}
                            alt={`বিকল্প ${LETTERS[i]}`}
                            className="max-w-full rounded-lg mt-2 border border-gray-200 dark:border-zinc-700"
                          />
                        )}
                      </span>
                      {isCorrect && (
                        <span className="shrink-0 self-center text-[11px] font-extrabold tracking-wide text-green-700 dark:text-green-300 bg-green-100 dark:bg-green-900/50 border border-green-200 dark:border-green-800 rounded-full px-2.5 py-1 whitespace-nowrap">
                          সঠিক উত্তর
                        </span>
                      )}
                    </div>
                  );
                })}
              </div>

              <div className="flex items-start gap-3 mt-5 p-4 rounded-xl bg-green-50 dark:bg-green-950/30 border border-green-200 dark:border-green-900">
                <span className="shrink-0 w-7 h-7 grid place-items-center rounded-full bg-green-500 text-white">
                  <Check size={16} strokeWidth={3} />
                </span>
                <span className="min-w-0">
                  <span className="block text-[11px] font-extrabold tracking-[0.09em] uppercase text-green-700 dark:text-green-400 mb-0.5">
                    সঠিক উত্তর
                  </span>
                  <span className="font-serif-bn text-lg font-semibold text-gray-900 dark:text-white leading-[1.75]">
                    {LETTERS[question.correctAnswerIndex]}. {question.options?.[question.correctAnswerIndex]}
                  </span>
                </span>
              </div>

              {question.explanation || question.explanationImage ? (
                <div className="mt-4 p-5 rounded-xl bg-slate-50 dark:bg-zinc-800/60 border border-gray-200 dark:border-zinc-700 border-l-4 border-l-primary">
                  <h2 className="flex items-center gap-2 text-[12px] font-extrabold tracking-[0.1em] uppercase text-orange-700 dark:text-orange-300 mb-2.5">
                    <Sparkles size={14} /> ব্যাখ্যা
                  </h2>
                  <div className="text-[16px] md:text-[17px] text-gray-700 dark:text-gray-300 whitespace-pre-wrap leading-[2]">
                    {question.explanation}
                  </div>
                  {question.explanationImage && (
                    <img
                      src={question.explanationImage}
                      alt="ব্যাখ্যার চিত্র"
                      className="max-w-full rounded-lg mt-3 border border-gray-200 dark:border-zinc-700"
                    />
                  )}
                </div>
              ) : (
                <div className="mt-4 p-4 rounded-xl bg-amber-50 dark:bg-amber-950/30 border border-dashed border-amber-300 dark:border-amber-800 text-[15px] text-amber-800 dark:text-amber-300 leading-[1.8]">
                  এই প্রশ্নটির বিস্তারিত ব্যাখ্যা এখনো যোগ করা হয়নি। AI টিউটরকে জিজ্ঞেস করলে সাথে সাথে সমাধান পেয়ে যাবে।
                </div>
              )}

              <div className="mt-6 flex flex-col sm:flex-row gap-3">
                <Link
                  to={qbankHref}
                  className="flex-1 flex items-center justify-center gap-2 px-5 py-3 bg-primary hover:bg-orange-600 text-white text-sm font-bold rounded-xl shadow-lg shadow-orange-500/20"
                >
                  <BookOpen size={16} /> এই অধ্যায়ে ফ্রি প্র্যাকটিস করো
                </Link>
                <Link
                  to="/qbank"
                  className="flex-1 flex items-center justify-center gap-2 px-5 py-3 border border-gray-200 dark:border-zinc-700 text-sm font-bold rounded-xl text-gray-700 dark:text-gray-200 hover:border-primary"
                >
                  সব প্রশ্নব্যাংক
                </Link>
              </div>
            </article>

            {/* ---- related ---- */}
            {related.length > 0 && (
              <section>
                <h2 className="text-lg font-bold text-gray-900 dark:text-white mb-3">একই অধ্যায়ের আরও প্রশ্ন</h2>
                <div className="grid gap-2">
                  {related.map((r, i) => (
                    <Link
                      key={r.id || i}
                      to={`/question/${r.slug || bnSlug(r.question)}`}
                      className="flex items-start gap-3 bg-white dark:bg-zinc-900 border border-gray-200 dark:border-zinc-800 rounded-xl px-4 py-3 hover:border-orange-300 dark:hover:border-orange-800 transition-colors"
                    >
                      <span className="shrink-0 w-6 h-6 grid place-items-center rounded-md bg-slate-50 dark:bg-zinc-800 border border-gray-200 dark:border-zinc-700 text-[11px] font-bold text-gray-500 dark:text-gray-400 mt-0.5">
                        {i + 1}
                      </span>
                      <span className="flex-1 min-w-0 text-[15px] font-medium text-gray-700 dark:text-gray-300 leading-[1.75]">
                        {r.question}
                      </span>
                      <ChevronRight size={16} className="shrink-0 text-gray-400 mt-1" />
                    </Link>
                  ))}
                </div>
                <Link to={qbankHref} className="inline-flex items-center gap-2 mt-3 text-sm font-bold text-primary hover:text-orange-600">
                  এই অধ্যায়ের সব প্রশ্ন দেখো <ChevronRight size={15} />
                </Link>
              </section>
            )}
          </div>
        )}
      </div>
    </div>
  );
};

export default QuestionPage;
