import React, { useEffect, useMemo, useRef, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import { ArrowLeft, CheckCircle2, Eye, Share2, BookOpen, Sparkles } from 'lucide-react';
import { fetchQuestionsFromBankAPI } from '../services/api';
import { QuizQuestion } from '../types';

/**
 * Public, no-auth question viewer.
 *
 * Revives the old (dead) share links  /#/question/<slug-or-id>  and acts as
 * the in-app counterpart of the static SEO pages at  /q/<slug>/  generated by
 * scripts/generate-seo-pages.mjs. Kept `noindex` on purpose: the indexable
 * canonical version of a question is its static page; this route exists so
 * that every shared link (all 50k+ questions, not just the static subset)
 * resolves inside the app.
 *
 * Visual language matches the warm-editorial design (paper/ink/brand/lime)
 * and the static SEO pages, with full dark-mode support.
 */

const LETTERS = ['ক', 'খ', 'গ', 'ঘ', 'ঙ', 'চ'];

function bnSlug(text: string) {
  return String(text)
    .normalize('NFC')
    .replace(/[\u200B-\u200D\uFEFF]/g, '')
    .replace(/\\[a-zA-Z]+/g, ' ')
    .replace(/[$^_{}~\\]/g, ' ')
    .replace(/[()[\]<>«»"'`.,;:!?!…।,]/g, ' ')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 70);
}

const QuestionPage: React.FC = () => {
  const { slug = '' } = useParams<{ slug: string }>();
  const [question, setQuestion] = useState<QuizQuestion | null>(null);
  const [state, setState] = useState<'loading' | 'ready' | 'notfound'>('loading');
  const [revealed, setRevealed] = useState(false);
  const bodyRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    let cancelled = false;
    setState('loading');
    setQuestion(null);
    setRevealed(false);

    const matches = (q: QuizQuestion) =>
      q.slug === slug || bnSlug(q.question) === slug || (q as any)._id === slug || q.id === slug;

    const tryFetch = async (search: string) => {
      const res = await fetchQuestionsFromBankAPI(1, 30, undefined, undefined, undefined, undefined, search);
      return (res?.questions || []) as QuizQuestion[];
    };

    (async () => {
      try {
        // slug is a dashed form of the question text → text search narrows it down
        let list = await tryFetch(slug.replace(/-/g, ' '));
        let found = list.find(matches);
        if (!found && slug.includes('-')) {
          list = await tryFetch(slug);
          found = list.find(matches);
        }
        if (!cancelled) {
          if (found) {
            setQuestion(found);
            setState('ready');
          } else {
            setState('notfound');
          }
        }
      } catch {
        if (!cancelled) setState('notfound');
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [slug]);

  // Typeset TeX once content is in the DOM (MathJax is lazy-loaded app-wide)
  useEffect(() => {
    if (state !== 'ready') return;
    let tries = 0;
    const timer = window.setInterval(() => {
      const M = (window as any).MathJax;
      if (M?.typesetPromise && bodyRef.current) {
        M.typesetPromise([bodyRef.current]).catch(() => {});
        window.clearInterval(timer);
      } else if (++tries > 8) {
        window.clearInterval(timer);
      }
    }, 500);
    return () => window.clearInterval(timer);
  }, [state]);

  const shareUrl = useMemo(
    () => `${window.location.origin}/q/${question?.slug || slug}/`,
    [question, slug]
  );

  const handleShare = () => {
    if (navigator.share) {
      navigator.share({ title: question?.question || 'পরীক্ষাঙ্গন', url: shareUrl }).catch(() => {});
    } else {
      navigator.clipboard?.writeText(shareUrl).catch(() => {});
    }
  };

  return (
    <div className="pk-landing dash relative w-full min-h-[80vh] overflow-hidden bg-paper dark:bg-ink text-ink dark:text-paper">
      <Helmet>
        <title>{question ? `${question.question.slice(0, 60)} | পরীক্ষাঙ্গন` : 'প্রশ্ন | পরীক্ষাঙ্গন'}</title>
        <meta name="robots" content="noindex, follow" />
      </Helmet>

      {/* Ambient warm washes + dot-grid paper texture */}
      <div aria-hidden className="pointer-events-none absolute inset-x-0 top-0 h-72 bg-[radial-gradient(60%_60%_at_50%_0%,rgba(255,82,0,0.09),transparent)] blur-2xl" />
      <div aria-hidden className="pointer-events-none absolute -top-20 -right-24 w-72 h-72 bg-[radial-gradient(closest-side,rgba(255,185,46,0.14),transparent)] blur-3xl" />
      <div aria-hidden className="pointer-events-none absolute inset-0 bg-[radial-gradient(rgba(22,18,16,0.04)_1px,transparent_1px)] dark:bg-[radial-gradient(rgba(255,255,255,0.05)_1px,transparent_1px)] [background-size:22px_22px]" />

      {/* Dark brand bar (matches static SEO pages) */}
      <header className="relative z-20 bg-ink shadow-[0_10px_30px_-18px_rgba(22,18,16,0.6)]">
        <div className="max-w-3xl mx-auto px-4 py-3 flex items-center justify-between gap-3">
          <Link to="/" className="flex items-center gap-2.5 text-paper font-bold text-[17px]">
            <span className="w-8 h-8 rounded-xl ring-conic grid place-items-center text-white font-extrabold shadow-md">প</span>
            পরীক্ষাঙ্গন
          </Link>
          <Link
            to="/auth"
            className="bg-lime text-ink font-extrabold text-sm px-4 py-2 rounded-full shadow-[0_10px_24px_-10px_rgba(255,185,46,0.6)] transition-transform hover:-translate-y-0.5"
          >
            ফ্রি শুরু করো
          </Link>
        </div>
      </header>

      <div className="max-w-3xl mx-auto relative z-10 py-8 px-4">
        <div className="flex items-center justify-between mb-5">
          <Link
            to="/qbank"
            className="focus-ring flex items-center gap-2 text-sm font-bold text-mist hover:text-brand-deep dark:hover:text-brand-bright transition-colors"
          >
            <ArrowLeft size={16} /> প্রশ্নব্যাংকে ফিরে যাও
          </Link>
          <button
            onClick={handleShare}
            className="focus-ring flex items-center gap-2 rounded-full bg-white/70 dark:bg-white/10 backdrop-blur-md px-4 py-2 text-sm font-bold text-ink dark:text-paper ring-1 ring-ink/10 dark:ring-white/15 shadow-sm hover:shadow transition-all"
          >
            <Share2 size={16} className="text-brand-deep dark:text-brand-bright" /> শেয়ার
          </button>
        </div>

        {state === 'loading' && (
          <div className="flex flex-col items-center justify-center py-24 text-mist">
            <div className="w-10 h-10 border-4 border-brand border-t-transparent rounded-full animate-spin mb-4" />
            <p className="text-sm font-bold">প্রশ্ন লোড হচ্ছে…</p>
          </div>
        )}

        {state === 'notfound' && (
          <div className="bg-white dark:bg-ink-2 ring-1 ring-ink/10 dark:ring-white/10 rounded-[26px] p-8 text-center shadow-[0_24px_60px_-28px_rgba(22,18,16,0.3)]">
            <h1 className="font-bangla text-xl md:text-2xl font-extrabold text-ink dark:text-paper mb-2">
              প্রশ্নটি খুঁজে পাওয়া যায়নি
            </h1>
            <p className="text-sm text-mist mb-6">
              লিংকটি পুরনো বা প্রশ্নটি মুছে ফেলা হয়ে থাকতে পারে। প্রশ্নব্যাংকে সার্চ করে দেখো।
            </p>
            <div className="flex justify-center gap-3 flex-wrap">
              <Link
                to="/qbank"
                className="focus-ring px-5 py-2.5 bg-brand hover:bg-brand-deep text-white text-sm font-bold rounded-full shadow-[0_12px_28px_-12px_rgba(255,82,0,0.6)] transition-all hover:-translate-y-0.5"
              >
                প্রশ্নব্যাংক খোলো
              </Link>
              <a
                href={`${import.meta.env.BASE_URL}hsc-syllabus/`}
                className="focus-ring px-5 py-2.5 ring-1 ring-ink/15 dark:ring-white/20 text-sm font-bold rounded-full text-ink dark:text-paper hover:ring-brand/40 transition-all"
              >
                সিলেবাস গাইড
              </a>
            </div>
          </div>
        )}

        {state === 'ready' && question && (
          <article
            ref={bodyRef as any}
            className="relative overflow-hidden bg-white dark:bg-ink-2 ring-1 ring-ink/10 dark:ring-white/10 rounded-[28px] p-5 md:p-8 shadow-[0_30px_70px_-32px_rgba(22,18,16,0.25)]"
          >
            <div aria-hidden className="absolute top-0 inset-x-0 h-[5px] bg-gradient-to-r from-brand via-lime to-brand" />
            <div className="flex flex-wrap gap-2 mb-4">
              {question.examRef && (
                <span className="text-xs font-bold px-3 py-1 rounded-full bg-lime-soft text-[#7a4d00] ring-1 ring-lime/40 dark:bg-gold/20 dark:text-gold dark:ring-gold/30">
                  সূত্র: {question.examRef}
                </span>
              )}
              {question.subject && (
                <span className="text-xs font-bold px-3 py-1 rounded-full bg-mint text-brand-deep dark:bg-brand/20 dark:text-brand-bright ring-1 ring-brand/15 dark:ring-brand/30">
                  {question.subject}
                </span>
              )}
              {question.chapter && (
                <span className="text-xs font-bold px-3 py-1 rounded-full bg-cream text-ink/70 dark:bg-white/10 dark:text-white/70 ring-1 ring-ink/10 dark:ring-white/10">
                  {question.chapter}
                </span>
              )}
              {(question.tags || []).slice(0, 2).map((t) => (
                <span key={t} className="text-xs font-bold px-3 py-1 rounded-full bg-ink/5 text-mist dark:bg-white/5 dark:text-white/50 ring-1 ring-ink/10 dark:ring-white/10">
                  {t}
                </span>
              ))}
            </div>

            <h1 className="font-bangla text-xl md:text-[26px] font-extrabold text-ink dark:text-paper leading-relaxed mb-5 tracking-tight after:content-[''] after:block after:w-[76px] after:h-[5px] after:rounded-full after:mt-4 after:bg-gradient-to-r after:from-brand after:to-lime">
              {question.question}
            </h1>
            {question.questionImage && (
              <img src={question.questionImage} alt="প্রশ্নের চিত্র" className="max-w-full rounded-2xl mb-4" />
            )}

            <div className="grid gap-2.5 mb-5">
              {(question.options || []).map((opt, i) => {
                const isCorrect = i === question.correctAnswerIndex;
                return (
                  <div
                    key={i}
                    className={[
                      'flex items-start gap-3 rounded-2xl border px-4 py-3 text-sm md:text-base transition-colors',
                      revealed && isCorrect
                        ? 'border-green-500/50 bg-green-50 dark:bg-green-950/40 font-bold text-green-800 dark:text-green-300'
                        : 'border-ink/10 dark:border-white/10 bg-paper dark:bg-white/5 text-ink/85 dark:text-white/85 transition-all hover:-translate-y-0.5 hover:border-brand/40 hover:shadow-[0_14px_30px_-18px_rgba(22,18,16,0.25)]',
                    ].join(' ')}
                  >
                    <span
                      className={[
                        'w-8 h-8 md:w-9 md:h-9 rounded-xl grid place-items-center font-bold shrink-0 text-sm',
                        revealed && isCorrect
                          ? 'bg-green-600 text-white'
                          : 'bg-mint text-brand-deep dark:bg-white/10 dark:text-brand-bright',
                      ].join(' ')}
                    >
                      {LETTERS[i]}
                    </span>
                    <span className="flex-1">
                      {opt}
                      {question.optionsImages?.[i] && (
                        <img src={question.optionsImages[i]} alt={`বিকল্প ${LETTERS[i]}`} className="max-w-full rounded-xl mt-2" />
                      )}
                    </span>
                    {revealed && isCorrect && <CheckCircle2 size={18} className="text-green-600 shrink-0 mt-0.5" />}
                  </div>
                );
              })}
            </div>

            {!revealed ? (
              <button
                onClick={() => setRevealed(true)}
                className="focus-ring w-full flex items-center justify-center gap-2 px-5 py-3.5 bg-brand hover:bg-brand-deep text-white font-bold rounded-full shadow-[0_16px_36px_-14px_rgba(255,82,0,0.65)] transition-all hover:-translate-y-0.5"
              >
                <Eye size={18} /> উত্তর ও ব্যাখ্যা দেখো
              </button>
            ) : (
              <div className="space-y-4">
                <div className="flex items-start gap-3.5 rounded-2xl border border-green-200 dark:border-green-900 bg-green-50 dark:bg-green-950/30 px-4 py-3.5 text-sm md:text-base">
                  <span className="flex-none w-10 h-10 rounded-full bg-green-600 text-white grid place-items-center font-extrabold text-lg shadow-[0_10px_22px_-10px_rgba(22,163,74,0.7)]">
                    ✓
                  </span>
                  <div>
                    <b className="text-green-700 dark:text-green-400">সঠিক উত্তর:</b>{' '}
                    <span className="text-ink dark:text-white">
                      {LETTERS[question.correctAnswerIndex]}. {question.options?.[question.correctAnswerIndex]}
                    </span>
                  </div>
                </div>
                {question.explanation && (
                  <div className="rounded-2xl border border-brand/15 dark:border-white/10 border-l-4 border-l-brand dark:border-l-brand-bright bg-cream dark:bg-white/5 px-4 py-4">
                    <h2 className="flex items-center gap-2 font-bangla text-sm font-extrabold text-ink dark:text-paper mb-2">
                      <Sparkles size={16} className="text-brand dark:text-brand-bright" /> ব্যাখ্যা
                    </h2>
                    <div className="text-sm md:text-base text-ink/75 dark:text-white/75 whitespace-pre-wrap leading-relaxed">
                      {question.explanation}
                    </div>
                    {question.explanationImage && (
                      <img src={question.explanationImage} alt="ব্যাখ্যার চিত্র" className="max-w-full rounded-xl mt-3" />
                    )}
                  </div>
                )}
              </div>
            )}

            <div className="mt-6 flex flex-col sm:flex-row gap-3">
              <Link
                to={`/qbank?level=ACADEMIC&subject=${encodeURIComponent(question.subject || '')}&chapter=${encodeURIComponent(question.chapter || '')}`}
                className="focus-ring flex-1 flex items-center justify-center gap-2 px-5 py-3 bg-ink dark:bg-lime hover:bg-brand-deep dark:hover:bg-gold text-paper dark:text-ink text-sm font-bold rounded-full transition-all hover:-translate-y-0.5 shadow-[0_16px_36px_-16px_rgba(22,18,16,0.5)]"
              >
                <BookOpen size={16} /> এই অধ্যায়ের আরও প্রশ্ন সলভ করো
              </Link>
              <a
                href={`/hsc-syllabus/`}
                className="focus-ring flex-1 flex items-center justify-center gap-2 px-5 py-3 ring-1 ring-ink/15 dark:ring-white/20 text-sm font-bold rounded-full text-ink dark:text-paper hover:ring-brand/40 transition-all"
              >
                সিলেবাস গাইড দেখো
              </a>
            </div>
          </article>
        )}
      </div>
    </div>
  );
};

export default QuestionPage;
