import React, { useEffect, useMemo, useRef, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import { ArrowLeft, CheckCircle2, Eye, Share2, BookOpen, Sparkles } from 'lucide-react';
import { fetchQuestionsFromBankAPI } from '../services/api';
import { QuizQuestion } from '../types';

/**
 * Public, no-auth question viewer.
 *
 * Revives the old (dead) share links  /#/question/<slug-or-id>  and acts as
 * the in-app counterpart of the static SEO pages at  /q/<slug>/  generated by
 * scripts/generate-seo-pages.mjs. Kept `noindex` on purpose: the indexable
 * canonical version of a question is its static page; this route exists so
 * that every shared link (all 50k+ questions, not just the static subset)
 * resolves inside the app.
 */

const LETTERS = ['ক', 'খ', 'গ', 'ঘ', 'ঙ', 'চ'];

function bnSlug(text: string) {
  return String(text)
    .normalize('NFC')
    .replace(/[\u200B-\u200D\uFEFF]/g, '')
    .replace(/\\[a-zA-Z]+/g, ' ')
    .replace(/[$^_{}~\\]/g, ' ')
    .replace(/[()[\]<>«»"'`.,;:!?!…।,]/g, ' ')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 70);
}

const QuestionPage: React.FC = () => {
  const { slug = '' } = useParams<{ slug: string }>();
  const [question, setQuestion] = useState<QuizQuestion | null>(null);
  const [state, setState] = useState<'loading' | 'ready' | 'notfound'>('loading');
  const [revealed, setRevealed] = useState(false);
  const bodyRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    let cancelled = false;
    setState('loading');
    setQuestion(null);
    setRevealed(false);

    const matches = (q: QuizQuestion) =>
      q.slug === slug || bnSlug(q.question) === slug || (q as any)._id === slug || q.id === slug;

    const tryFetch = async (search: string) => {
      const res = await fetchQuestionsFromBankAPI(1, 30, undefined, undefined, undefined, undefined, search);
      return (res?.questions || []) as QuizQuestion[];
    };

    (async () => {
      try {
        // slug is a dashed form of the question text → text search narrows it down
        let list = await tryFetch(slug.replace(/-/g, ' '));
        let found = list.find(matches);
        if (!found && slug.includes('-')) {
          list = await tryFetch(slug);
          found = list.find(matches);
        }
        if (!cancelled) {
          if (found) {
            setQuestion(found);
            setState('ready');
          } else {
            setState('notfound');
          }
        }
      } catch {
        if (!cancelled) setState('notfound');
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [slug]);

  // Typeset TeX once content is in the DOM (MathJax is lazy-loaded app-wide)
  useEffect(() => {
    if (state !== 'ready') return;
    let tries = 0;
    const timer = window.setInterval(() => {
      const M = (window as any).MathJax;
      if (M?.typesetPromise && bodyRef.current) {
        M.typesetPromise([bodyRef.current]).catch(() => {});
        window.clearInterval(timer);
      } else if (++tries > 8) {
        window.clearInterval(timer);
      }
    }, 500);
    return () => window.clearInterval(timer);
  }, [state]);

  const shareUrl = useMemo(
    () => `${window.location.origin}/q/${question?.slug || slug}/`,
    [question, slug]
  );

  const handleShare = () => {
    if (navigator.share) {
      navigator.share({ title: question?.question || 'পরীক্ষাঙ্গন', url: shareUrl }).catch(() => {});
    } else {
      navigator.clipboard?.writeText(shareUrl).catch(() => {});
    }
  };

  return (
    <div className="w-full min-h-[80vh] bg-slate-50/50 dark:bg-gray-950 py-6 px-4">
      <Helmet>
        <title>{question ? `${question.question.slice(0, 60)} | পরীক্ষাঙ্গন` : 'প্রশ্ন | পরীক্ষাঙ্গন'}</title>
        <meta name="robots" content="noindex, follow" />
      </Helmet>

      <div className="max-w-3xl mx-auto">
        <div className="flex items-center justify-between mb-4">
          <Link
            to="/qbank"
            className="flex items-center gap-2 text-sm font-semibold text-gray-600 dark:text-gray-300 hover:text-primary dark:hover:text-purple-700 dark:text-purple-400"
          >
            <ArrowLeft size={16} /> প্রশ্নব্যাংকে ফিরে যাও
          </Link>
          <button
            onClick={handleShare}
            className="flex items-center gap-2 text-sm font-semibold text-gray-600 dark:text-gray-300 hover:text-primary dark:hover:text-purple-700 dark:text-purple-400"
          >
            <Share2 size={16} /> শেয়ার
          </button>
        </div>

        {state === 'loading' && (
          <div className="flex flex-col items-center justify-center py-24 text-gray-400">
            <div className="w-10 h-10 border-4 border-purple-500 border-t-transparent rounded-full animate-spin mb-4" />
            <p className="text-sm font-semibold">প্রশ্ন লোড হচ্ছে…</p>
          </div>
        )}

        {state === 'notfound' && (
          <div className="bg-white dark:bg-zinc-900 border border-gray-200 dark:border-zinc-800 rounded-2xl p-8 text-center">
            <h1 className="text-xl font-bold text-gray-900 dark:text-white mb-2">প্রশ্নটি খুঁজে পাওয়া যায়নি</h1>
            <p className="text-sm text-gray-500 dark:text-gray-400 mb-6">
              লিংকটি পুরনো বা প্রশ্নটি মুছে ফেলা হয়ে থাকতে পারে। প্রশ্নব্যাংকে সার্চ করে দেখো।
            </p>
            <div className="flex justify-center gap-3">
              <Link to="/qbank" className="px-5 py-2.5 bg-primary hover:bg-purple-600 text-white text-sm font-bold rounded-xl">
                প্রশ্নব্যাংক খোলো
              </Link>
              <a href={`${import.meta.env.BASE_URL}hsc-syllabus/`} className="px-5 py-2.5 border border-gray-200 dark:border-zinc-700 text-sm font-bold rounded-xl text-gray-700 dark:text-gray-200">
                সিলেবাস গাইড
              </a>
            </div>
          </div>
        )}

        {state === 'ready' && question && (
          <div ref={bodyRef} className="bg-white dark:bg-zinc-900 border border-gray-200 dark:border-zinc-800 rounded-2xl p-5 md:p-8">
            <div className="flex flex-wrap gap-2 mb-4">
              {question.subject && (
                <span className="text-xs font-bold px-3 py-1 rounded-full bg-purple-100 text-purple-700 dark:bg-purple-950 dark:text-purple-300">
                  {question.subject}
                </span>
              )}
              {question.chapter && (
                <span className="text-xs font-bold px-3 py-1 rounded-full bg-gray-100 text-gray-600 dark:bg-zinc-800 dark:text-gray-300">
                  {question.chapter}
                </span>
              )}
              {(question.tags || []).slice(0, 2).map((t) => (
                <span key={t} className="text-xs font-bold px-3 py-1 rounded-full bg-gray-100 text-gray-500 dark:bg-zinc-800 dark:text-gray-400">
                  {t}
                </span>
              ))}
            </div>

            <h1 className="text-lg md:text-2xl font-bold text-gray-900 dark:text-white leading-relaxed mb-4">
              {question.question}
            </h1>
            {question.questionImage && (
              <img src={question.questionImage} alt="প্রশ্নের চিত্র" className="max-w-full rounded-xl mb-4" />
            )}

            <div className="grid gap-2.5 mb-5">
              {(question.options || []).map((opt, i) => {
                const isCorrect = i === question.correctAnswerIndex;
                return (
                  <div
                    key={i}
                    className={[
                      'flex items-start gap-3 rounded-xl border px-4 py-3 text-sm md:text-base',
                      revealed && isCorrect
                        ? 'border-green-500 bg-green-50 dark:bg-green-950/40 font-bold text-green-800 dark:text-green-300'
                        : 'border-gray-200 dark:border-zinc-700 text-gray-800 dark:text-gray-200',
                    ].join(' ')}
                  >
                    <span className="font-bold shrink-0">{LETTERS[i]}.</span>
                    <span className="flex-1">
                      {opt}
                      {question.optionsImages?.[i] && (
                        <img src={question.optionsImages[i]} alt={`বিকল্প ${LETTERS[i]}`} className="max-w-full rounded-lg mt-2" />
                      )}
                    </span>
                    {revealed && isCorrect && <CheckCircle2 size={18} className="text-green-600 shrink-0 mt-0.5" />}
                  </div>
                );
              })}
            </div>

            {!revealed ? (
              <button
                onClick={() => setRevealed(true)}
                className="w-full flex items-center justify-center gap-2 px-5 py-3 bg-primary hover:bg-purple-600 text-white font-bold rounded-xl transition-colors"
              >
                <Eye size={18} /> উত্তর ও ব্যাখ্যা দেখো
              </button>
            ) : (
              <div className="space-y-4">
                <div className="rounded-xl border border-green-200 dark:border-green-900 bg-green-50 dark:bg-green-950/30 px-4 py-3 text-sm md:text-base">
                  <b className="text-green-700 dark:text-green-400">সঠিক উত্তর:</b>{' '}
                  <span className="text-gray-800 dark:text-gray-100">
                    {LETTERS[question.correctAnswerIndex]}. {question.options?.[question.correctAnswerIndex]}
                  </span>
                </div>
                {question.explanation && (
                  <div className="rounded-xl border border-gray-200 dark:border-zinc-700 bg-slate-50 dark:bg-zinc-800/60 px-4 py-4">
                    <h2 className="flex items-center gap-2 text-sm font-bold text-gray-700 dark:text-gray-200 mb-2">
                      <Sparkles size={16} className="text-primary" /> ব্যাখ্যা
                    </h2>
                    <div className="text-sm md:text-base text-gray-700 dark:text-gray-300 whitespace-pre-wrap">
                      {question.explanation}
                    </div>
                    {question.explanationImage && (
                      <img src={question.explanationImage} alt="ব্যাখ্যার চিত্র" className="max-w-full rounded-lg mt-3" />
                    )}
                  </div>
                )}
              </div>
            )}

            <div className="mt-6 flex flex-col sm:flex-row gap-3">
              <Link
                to={`/qbank?level=ACADEMIC&subject=${encodeURIComponent(question.subject || '')}&chapter=${encodeURIComponent(question.chapter || '')}`}
                className="flex-1 flex items-center justify-center gap-2 px-5 py-3 bg-primary hover:bg-purple-600 text-white text-sm font-bold rounded-xl"
              >
                <BookOpen size={16} /> এই অধ্যায়ের আরও প্রশ্ন সলভ করো
              </Link>
              <a
                href={`/hsc-syllabus/`}
                className="flex-1 flex items-center justify-center gap-2 px-5 py-3 border border-gray-200 dark:border-zinc-700 text-sm font-bold rounded-xl text-gray-700 dark:text-gray-200 hover:border-primary"
              >
                সিলেবাস গাইড দেখো
              </a>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default QuestionPage;
